name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          repository: uyamazak/firebase-auth-emulator
          tag_with_ref: true
